banner:
  charset: UTF-8 # Banner file encoding.
  location: classpath:banner.txt # Banner file location.

logging:
  level:
     org.springframework.web: DEBUG
     guru.springframework.controllers: DEBUG
     org.hibernate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roxanne_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: roxanne
    password: roxanne
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
